# Generated by Django 4.2.3 on 2023-08-24 07:39

import app_food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodtable',
            fields=[
                ('Food_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_food_th', models.CharField(max_length=150, validators=[app_food.models.validate_at_least_one_name])),
                ('name_of_food_eng', models.CharField(max_length=150, validators=[app_food.models.validate_at_least_one_name])),
                ('kcal', models.FloatField(blank=True, null=True)),
                ('water', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('carb', models.FloatField(blank=True, null=True)),
                ('dietary_fiber', models.FloatField(blank=True, null=True)),
                ('ash', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('magnesium', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('protassium', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
                ('copper', models.FloatField(blank=True, null=True)),
                ('zinc', models.FloatField(blank=True, null=True)),
                ('iodine', models.FloatField(blank=True, null=True)),
                ('betacarotene', models.FloatField(blank=True, null=True)),
                ('retinol', models.FloatField(blank=True, null=True)),
                ('RAE', models.FloatField(blank=True, null=True)),
                ('thiamin', models.FloatField(blank=True, null=True)),
                ('riboflavin', models.FloatField(blank=True, null=True)),
                ('niacin', models.FloatField(blank=True, null=True)),
                ('vitamin_C', models.FloatField(blank=True, null=True)),
                ('vitamin_E', models.FloatField(blank=True, null=True)),
                ('sugar', models.FloatField(blank=True, null=True)),
                ('vegan', models.BooleanField(default=False)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'foodtable',
            },
        ),
    ]
